# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/natalia/Documents/GitHub/FEMCourse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/natalia/Documents/GitHub/FEMCourse

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natalia/Documents/GitHub/FEMCourse/CMakeFiles /home/natalia/Documents/GitHub/FEMCourse/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natalia/Documents/GitHub/FEMCourse/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Fem2018

# Build rule for target.
Fem2018: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Fem2018
.PHONY : Fem2018

# fast build rule for target.
Fem2018/fast:
	$(MAKE) -f mainprograms/CMakeFiles/Fem2018.dir/build.make mainprograms/CMakeFiles/Fem2018.dir/build
.PHONY : Fem2018/fast

#=============================================================================
# Target rules for targets named TestMatrix

# Build rule for target.
TestMatrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestMatrix
.PHONY : TestMatrix

# fast build rule for target.
TestMatrix/fast:
	$(MAKE) -f mainprograms/CMakeFiles/TestMatrix.dir/build.make mainprograms/CMakeFiles/TestMatrix.dir/build
.PHONY : TestMatrix/fast

#=============================================================================
# Target rules for targets named FemSC

# Build rule for target.
FemSC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FemSC
.PHONY : FemSC

# fast build rule for target.
FemSC/fast:
	$(MAKE) -f mainprograms/CMakeFiles/FemSC.dir/build.make mainprograms/CMakeFiles/FemSC.dir/build
.PHONY : FemSC/fast

#=============================================================================
# Target rules for targets named TestIntegrate

# Build rule for target.
TestIntegrate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestIntegrate
.PHONY : TestIntegrate

# fast build rule for target.
TestIntegrate/fast:
	$(MAKE) -f mainprograms/CMakeFiles/TestIntegrate.dir/build.make mainprograms/CMakeFiles/TestIntegrate.dir/build
.PHONY : TestIntegrate/fast

#=============================================================================
# Target rules for targets named TestOneDProblem

# Build rule for target.
TestOneDProblem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestOneDProblem
.PHONY : TestOneDProblem

# fast build rule for target.
TestOneDProblem/fast:
	$(MAKE) -f mainprograms/CMakeFiles/TestOneDProblem.dir/build.make mainprograms/CMakeFiles/TestOneDProblem.dir/build
.PHONY : TestOneDProblem/fast

#=============================================================================
# Target rules for targets named TestTwoDProblem

# Build rule for target.
TestTwoDProblem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestTwoDProblem
.PHONY : TestTwoDProblem

# fast build rule for target.
TestTwoDProblem/fast:
	$(MAKE) -f mainprograms/CMakeFiles/TestTwoDProblem.dir/build.make mainprograms/CMakeFiles/TestTwoDProblem.dir/build
.PHONY : TestTwoDProblem/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Fem2018"
	@echo "... TestMatrix"
	@echo "... FemSC"
	@echo "... TestIntegrate"
	@echo "... TestOneDProblem"
	@echo "... TestTwoDProblem"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

